### ISSUE TITLE
Qt5 for windows/64bit patch, need help

### ISSUE THREAD

**Issue by chai2010** [go-qml/qml#98]
Qt5 don't support 64bit for MinGW64.
And mingw don't support static link with C++ on windows.
See https://code.google.com/p/go/issues/detail?id=4069

I create a fork for Qt5 with MSVC2012/2013:
https://github.com/chai2010/qml

It can work on Qt5/MSVC2012/64bit.

I hope to submit my patch.
But i am a newbie for git, give me some help?

Thanks!

**Comment by niemeyer** [comment]
Sure thing. The basic workflow for pull requests is described in this GitHub article:
- https://help.github.com/articles/using-pull-requests

The pull requests should be sent for individual improvements (small units), rather than for a complex branch that encompasses many independent/unrelated changes.

If you need more help, please come over to the mailing list so we can talk about it:
- https://groups.google.com/forum/#!forum/go-qml

**Comment by niemeyer** [comment]
By the way, are you able to have a look at issue #79 and see if you can report whether the suggested change works or not under your environment?

Thanks again.
